### ISSUE TITLE
Error: Refusing to load module...because it does not match any entry in the module allowlist

### ISSUE THREAD

**Issue by StefMa** [jasongwartz/pkl-playground#5]
Given I paste the following into the playground:
```pkl
amends "package://pkg.pkl-lang.org/github.com/stefma/pkl-gha/com.github.action@0.0.3#/GitHubAction.pkl"
import "https://someUrlSomewhere.com/Steps.pkl"

name = "AWorkflow"

on {
    pull_request {}
}


jobs {
    ["build"] {
        `runs-on` = "ubuntu-latest"
        steps {
            Steps.checkout
        }
    }
}

```
While the `Steps.pkl` has the following content:
```pkl
import "package://pkg.pkl-lang.org/github.com/stefma/pkl-gha/com.github.action@0.0.3#/GitHubAction.pkl"

checkout: GitHubAction.Step = new {
  name = "Checkout"
  uses = "actions/checkout@v4"
}
```

I get the following error:
```
Refusing to load module `https://someUrlSomehwere.com/Steps.pkl` because it does not match any entry in the module allowlist (`--allowed-modules`).
```

Locally, with `pkl 0.26.3` everything works as expected
```bash
pkl eval test.pkl
```
Yields to
```yml
# Do not modify!
# This file was generated from a template using https://github.com/StefMa/pkl-gha

name: AWorkflow
'on':
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
```

Maybe this is an problem on an old `pkl` version? 🤔 
This is why I also raised [this issue](https://github.com/pkl-community/node-packages/issues/8).
